version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  zeek:
    image: zeek/zeek
    volumes:
      - zeek-logs:/usr/local/zeek/logs
    command: zeekctl deploy
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - zeek-logs:/usr/local/zeek/logs/current:ro
    env_file:
      - .env
    depends_on:
      - influxdb
      - zeek

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
  zeek-logs:
