services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  slips:
    image: stratosphereips/slips_macos_m1:latest
    volumes:
      - slips-logs:/StratosphereLinuxIPS/output
    command: ["/bin/sh", "-c", "rm -rf /StratosphereLinuxIPS/output/* && ./slips.py -i eth0"]   # change interface for another app
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    # restart: unless-stopped

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:ro
      - slips-logs:/slips-logs:ro
    env_file:
      - .env
    depends_on:
      - influxdb
      - slips

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
  slips-logs:
